taco:
  orders:
    pageSize: 10

spring:
  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

