spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco-cloud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

loging:
  level:
    tacos: WARN